import type { DesignTokenCategory } from "./types";

/**
 * Deterministic serializer: design_token rows -> tokens.css (CSS custom
 * properties). Deliberately NOT an LLM call -- it's a pure transform of
 * data already resolved by Figma sync (src/lib/figma/sync.ts), so there's
 * nothing to generate, and this is the one file every component in the
 * design-system repo depends on (via var(--token-name)) -- keeping it
 * deterministic removes a source of nondeterminism from the thing
 * everything else is built on. Mirrors the format hand-written into the
 * design-system repo's own src/tokens/tokens.css starter file.
 */

export interface TokenForCss {
  name: string;
  category: DesignTokenCategory;
  value: string;
}

const CATEGORY_ORDER: DesignTokenCategory[] = ["color", "typography", "spacing", "radius", "shadow", "duration", "other"];

/** "Text Primary" / "text_primary" / "Label/Light/primary" -> "text-primary"
 *  / "label-light-primary". Same convention as Figma sync's own slugify
 *  (src/lib/figma/sync.ts), kept local here since the fallback-on-empty
 *  behavior differs (a token can't fall back to a generic name the way a
 *  component slug does -- an empty/unusable token name means the token
 *  should be skipped, not silently renamed).
 *
 *  Exported because component codegen MUST reference tokens by the SAME
 *  sanitized name this emits into tokens.css -- CSS custom properties are
 *  case-sensitive, so feeding the model the raw Figma name ("Label/Light/
 *  primary") makes it write var(--Label-Light-primary), which never resolves
 *  against tokens.css's --label-light-primary. */
export function toCssVarName(name: string): string {
  return name
    .toLowerCase()
    .trim()
    .replace(/[^a-z0-9]+/g, "-")
    .replace(/^-+|-+$/g, "");
}

export function generateTokensCss(tokens: TokenForCss[]): string {
  const byCategory = new Map<DesignTokenCategory, TokenForCss[]>();
  for (const token of tokens) {
    const varName = toCssVarName(token.name);
    if (!varName) continue; // unusable name (e.g. all-symbols) -- skip rather than emit invalid CSS
    const list = byCategory.get(token.category) ?? [];
    list.push({ ...token, name: varName });
    byCategory.set(token.category, list);
  }

  const lines: string[] = [
    "/*",
    " * Design tokens as CSS custom properties.",
    " *",
    " * Generated by ai-tools-app's Figma sync (src/lib/design-system-codegen/tokens.ts,",
    " * a deterministic serializer -- no LLM involved) and committed here via a pull",
    " * request. Hand edits will be overwritten by the next token sync -- change",
    " * values in Figma and resync instead.",
    " *",
    " * Components reference tokens via var(--token-name), never a hardcoded value,",
    " * so a resync updates every component at once.",
    " */",
    "",
    ":root {",
  ];

  for (const category of CATEGORY_ORDER) {
    const entries = byCategory.get(category);
    if (!entries || entries.length === 0) continue;
    lines.push(`  /* ${category} */`);
    for (const entry of entries.sort((a, b) => a.name.localeCompare(b.name))) {
      lines.push(`  --${entry.name}: ${entry.value};`);
    }
    lines.push("");
  }

  // Drop the trailing blank line from the loop above before closing the block.
  while (lines[lines.length - 1] === "") lines.pop();
  lines.push("}", "");

  return lines.join("\n");
}
